# Generated by Django 5.1.5 on 2025-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_userlogin_remove_user_is_admin_task_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
