# Generated by Django 5.1.5 on 2025-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
    ]
