# Generated by Django 5.1.5 on 2025-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_details_task_is_checked_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_edit',
            field=models.BooleanField(default=False),
        ),
    ]
