# Generated by Django 5.1.2 on 2025-01-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userlogin_delete_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='user_agent',
        ),
    ]
